apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-center
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-center
  template:
    metadata:
      labels:
        app: service-center
    spec:
      containers:
        - name: service-center
          image: servicecomb/service-center:latest
          ports:
            - containerPort: 30100
---
apiVersion: v1
kind: Service
metadata:
  name: service-center
spec:
  type: ClusterIP
  selector:
    app: service-center
  ports:
    - protocol: TCP
      port: 30100
      targetPort: 30100
